---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auftrag-6-2
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd-storagepool-cluster
  volumeMode: Filesystem
